post_install() {
	echo -e "---> Included are profiles for Firejail and profile-sync-daemon,"
	echo -e "---> which you can symlink from /usr/lib/plasmafox/distribution"
	echo -e "---> to /etc/firejail and /usr/share/psd/browsers respectively. \n"
}

post_upgrade() {
	echo -e "---> Included are profiles for Firejail and profile-sync-daemon,"
	echo -e "---> which you can symlink from /usr/lib/plasmafox/distribution"
	echo -e "---> to /etc/firejail and /usr/share/psd/browsers respectively. \n"
}
